/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_3 (
    input signed [15:0] a,
    input signed [15:0] b,
    input [5:0] alufn,
    output reg signed [15:0] out,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [15:0] s;
  
  reg xb15;
  
  always @* begin
    if (alufn[0+0-:1] == 1'h1) begin
      s = a - b;
    end else begin
      if (alufn[1+0-:1] == 1'h0) begin
        s = a + b;
      end else begin
        s = a * b;
      end
    end
    out = s;
    xb15 = alufn[0+0-:1] ^ b[15+0-:1];
    z = (~|s);
    v = (a[15+0-:1] & xb15 & ~s[15+0-:1]) | (~a[15+0-:1] & ~xb15 & s[15+0-:1]);
    n = s[15+0-:1];
  end
endmodule
