/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module multi_seven_seg_7 (
    input clk,
    input rst,
    input [31:0] word,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel
  );
  
  
  
  wire [8-1:0] M_seven_seg_lut_segs;
  reg [8-1:0] M_seven_seg_lut_char;
  seven_seg_lut_23 seven_seg_lut (
    .char(M_seven_seg_lut_char),
    .segs(M_seven_seg_lut_segs)
  );
  
  wire [4-1:0] M_num_to_seg_out;
  reg [2-1:0] M_num_to_seg_in;
  decoder_24 num_to_seg (
    .in(M_num_to_seg_in),
    .out(M_num_to_seg_out)
  );
  
  wire [2-1:0] M_seg_ctr_value;
  counter_25 seg_ctr (
    .clk(clk),
    .rst(rst),
    .value(M_seg_ctr_value)
  );
  
  always @* begin
    M_num_to_seg_in = M_seg_ctr_value;
    io_sel = ~M_num_to_seg_out;
    M_seven_seg_lut_char = word[(M_seg_ctr_value)*8+7-:8];
    io_seg = ~M_seven_seg_lut_segs;
  end
endmodule
